version: '3.1'

services:
  certbot:
    image: certbot/certbot
    ports:
    - "80:80"
    volumes:
    - ./volumes/certbot/etc/letsencrypt:/etc/letsencrypt
    command:
      certonly --webroot
      --standalone
      --register-unsafely-without-email --agree-tos
      --staging
      -d onlinegeniuses.net -d www.onlinegeniuses.net
      -v
